version: "3"

services:
  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"
  # RabbitMQ
  rabbit:
    image: rabbitmq:3.7.8
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"  # We forward this port because it's useful for debugging
