version: "3"

services:
  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"
  # RabbitMQ
  rabbit:
    image: rabbitmq:3.7.8
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"  # We forward this port because it's useful for debugging
  db:
    image: postgres:13
    restart: always
    networks:
      - django_network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=func_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
networks:
  django_network:

volumes:
  postgres_data: