# Generated by Django 3.2.6 on 2021-08-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=20)),
                ('interval', models.IntegerField()),
                ('picture', models.ImageField(upload_to='pictures/%Y/%m/%d/')),
                ('step', models.IntegerField()),
            ],
        ),
    ]
