# Generated by Django 3.2.6 on 2021-08-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_function_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='date_of_processing',
            field=models.DateTimeField(null=True),
        ),
    ]
