# Generated by Django 3.2.6 on 2021-08-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_function_date_of_processing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='interval',
            field=models.IntegerField(default=b'chert'),
        ),
    ]
