# Generated by Django 3.2.6 on 2021-09-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_function_interval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='function',
            options={'verbose_name': 'Функции', 'verbose_name_plural': 'Функции'},
        ),
        migrations.AlterField(
            model_name='function',
            name='date_of_processing',
            field=models.DateTimeField(null=True, verbose_name='Дата обработки'),
        ),
        migrations.AlterField(
            model_name='function',
            name='formula',
            field=models.CharField(max_length=20, verbose_name='Функция'),
        ),
        migrations.AlterField(
            model_name='function',
            name='interval',
            field=models.IntegerField(verbose_name='Интервал'),
        ),
        migrations.AlterField(
            model_name='function',
            name='picture',
            field=models.ImageField(null=True, upload_to='pictures/%Y/%m/%d/', verbose_name='График'),
        ),
        migrations.AlterField(
            model_name='function',
            name='step',
            field=models.IntegerField(verbose_name='Шаг'),
        ),
    ]
